### ISSUE TITLE
undefined symbol: _Z19ReadTransitionModelRN5kaldi15TransitionModelESsb

### ISSUE THREAD

**Issue by kakashidan** [idiap/pkwrap#16]
Hi
the process of installation seems ok. But I encountered some errors when import pkwrap. 

error message: `miniconda3/envs/pkwarp/lib/python3.9/site-packages/pkwrap-0.2.31.3-py3.9-linux-x86_64.egg/_pkwrap.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z19ReadTransitionModelRN5kaldi15TransitionModelESsb`

```
export TORCH_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
export GLIBCXX_USE_CXX11_ABI=0
export CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"
```
I checked kaldi with version `6f329a62 ` and compiled with above options with gcc 5.4.

Could you figure out the problem?

**Comment by mrsrikanth** [comment]
I have fixed this issue (that creeped in due to a bad merge from my side). I have fixed it now in the master. In addition, note that I have now added ``requirements.txt`` file, since soundfile is now a requirement. Make sure that you also have those packages installed as well.

Let me know if the issue persists. Thanks.

**Comment by mrsrikanth** [comment]
Also note that using ``6f329a62`` is no longer a requirement. The latest versions of Kaldi should work without issues. Otherwise, do let me know.

**Comment by kakashidan** [comment]
Thanks. 
this issue was solved after pulling the latest version of pkwrap.
