### ISSUE TITLE
 undefined symbol: _ZN5kaldi23SplitStringOnFirstSpaceERKSsPSsS2_

### ISSUE THREAD

**Issue by iezhanqingran** [idiap/pkwrap#21]
Hi,

When I run the script, I had the following errors

`Traceback (most recent call last):
  File "local/chain/train.py", line 16, in <module>
    import pkwrap
  File "/home/qzhan/anaconda3/lib/python3.7/site-packages/pkwrap-0.2.31.6-py3.7-linux-x86_64.egg/pkwrap/__init__.py", line 5, in <module>
    from _pkwrap import *
ImportError: /home/qzhan/anaconda3/lib/python3.7/site-packages/pkwrap-0.2.31.6-py3.7-linux-x86_64.egg/_pkwrap.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5kaldi23SplitStringOnFirstSpaceERKSsPSsS2_`

For both Kaldi and Pkwrap, I added 
`CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"`

The kaldi version is 'f1338f'

Thanks,
Qingran

**Comment by mrsrikanth** [comment]
Can you make sure the correct Kaldi libraries are in your `LD_LIBRARY_PATH`?

**Comment by iezhanqingran** [comment]
Hi,

Sorry, my kaldi version should be `94f3762`
and I checked the `LD_LIBRARY_PATH`, there is only one kaldi,
I did
`echo $LD_LIBRARY_PATH
`
`
:/home/qzhan/tools/kaldi/src/lib
`
For the `CXXFLAGS`, I think I compiled with `CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"`, but I will try it again.

**Comment by iezhanqingran** [comment]
I recompiled everything and now it works.
Thanks,
Qingran

**Comment by jyp0716** [comment]
@iezhanqingran
 I compiled with CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0", but I can not build kaldi successfully
In kaldi  tools folder, I build it with `make  CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -j 32`, but I met some errors, Can you help me ? Thanks

**Comment by iezhanqingran** [comment]
> @iezhanqingran I compiled with CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0", but I can not build kaldi successfully In kaldi tools folder, I build it with `make CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -j 32`, but I met some errors, Can you help me ? Thanks

Can you show the errors?

**Comment by jyp0716** [comment]
> > @iezhanqingran I compiled with CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0", but I can not build kaldi successfully In kaldi tools folder, I build it with `make CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -j 32`, but I met some errors, Can you help me ? Thanks
> 
> Can you show the errors?

ok, I show part logs
`/usr/bin/ld alignment_test.cpp: (.text+0x562): undefined reference to "TokenAlignmet::GetTokenFor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>,> const&)"`

I used:
 gcc -v  9.4
kaldi -v 66f5434

**Comment by mrsrikanth** [comment]
It looks like you have modified Kaldi code. There looks to be a typo in ``TokenAlignmet``. I am not able to find ``alignment_test.cpp`` either. 

Also, make sure the tools/ directory is compiled with the same flags. It is best to clean and compile from scratch.

**Comment by jyp0716** [comment]
> It looks like you have modified Kaldi code. There looks to be a typo in `TokenAlignmet`. I am not able to find `alignment_test.cpp` either.
> 
> Also, make sure the tools/ directory is compiled with the same flags. It is best to clean and compile from scratch.

Hi, 
I did not modify kaldi code
I git clone kaldi master branch and then compile tools/ directory with   `make CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -j 32`, then I meet some errors
If I compile with `make -j 32`, it build successfully

**Comment by mrsrikanth** [comment]
I tried to reproduce it and looks to me that this is a problem with sctk. If I skip installing it, everything else works.

**Comment by jyp0716** [comment]
Thanks, I will try to recompile without sctk---- Replied Message ----FromSrikanth M ***@***.***>Date11/17/2021 22:50 ***@***.***> ***@***.******@***.***>SubjectRe: [idiap/pkwrap] undefined symbol: _ZN5kaldi23SplitStringOnFirstSpaceERKSsPSsS2_ (#21)
I tried to reproduce it and looks to me that this is a problem with sctk. If I skip installing it, everything else works.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/idiap/pkwrap/issues/21#issuecomment-971655066",
"url": "https://github.com/idiap/pkwrap/issues/21#issuecomment-971655066",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jyp0716** [comment]
Thanks, I will try to recompile without sctk
